#!/bin/bash

# docs is the distribution directory
aws s3 sync --delete build s3://crunchypartoftheegg/forestcover-viz

# Because this website is behind a cloudfront distribution, we need to
# invalidate the cloudfront cache everytime we deploy
aws cloudfront create-invalidation --distribution-id E3QT85KXOB88Q --paths '/forestcover-viz*'
